---
title: "Time Series"
author: "Seonguk Choi"
date: "2023-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyr)
library(readxl)
library(dplyr)
library(stringr)

# save(data_2012_2022, file = "test.RData")
load("test.RData")
```

# Data

```{r}
dir_adj <- "../Population-raw/서울/"
file_list <- list.files(dir_adj)

get_year <- function(target_year) {
  final_data <- tibble()
  queue <- file_list[which(sapply(file_list, function(x) startsWith(x, as.character(target_year))))]
  
  for (file in queue) {
    suppressMessages( # silent new names messages
      data <- read_excel(paste0(dir_adj, file))
    )
    data <- data %>% slice(3:n())
    colnames(data) <- data[1, ]
    data <- data[-1, c(-1, -3, -4)] # 관련 없는 행, 열 제거
    data <- data %>% mutate(year = target_year)
    
    final_data <- bind_rows(final_data, data)
    
    print(paste0(file, "  done"))
  }
  
  return(final_data)
}
```


```{r}
merge_years <- function(given, year_from, year_to) {
  for (year in year_from:year_to) {
    data <- get_year(year)
    given <- bind_rows(given, data)
  }
  
  return(given)
}
```

```{r eval=FALSE}
data_2012_2022 <- merge_years(tibble(), 2012, 2022)
```

```{r}
data_2012_2022
```

```{r}
str_split("서울특별시 서울특별시 종로구", pattern = " ")[[1]]

data_2012_2022 %>% separate("행정기관", sep = " ", into = c("level1", "level2", "level3"))
```

